#!/bin/bash

#TODO:
#   expose port:
#       pod
#       svc
#       deployment
#   check:
#       make a flow
#   db:
#       restore from dump

###COLORLS###
#LIGHT COLORS#
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
GRAY='\033[0;37m'
#REGULAR COLORS#
DGRAY='\033[0;30m'
BLACK='\033[30m'
DRED='\033[31m'
YELLOW='\033[0;33m'
NC='\033[0m' #No color

###POD STATES###
PODOK=("Running")
PODERR=("CrashLoopBackOff" "Error" "Failed" "ImagePullBackOff" "ErrImagePull" "Unknow")
PODNONE=("Completed" "Terminating" "Init" "Waiting" "Pending" "ContainerCreating")


if [[ $USER != 'root' ]]; then
    if [[ ! -d "/home/$USER/.easykube/" ]]; then
        mkdir /home/$USER/.easykube/
    fi
    CONFIGFILE="/home/$USER/.easykube/config.json"
    CONNFILE="/home/$USER/.easykube/connections.json"
else
    if [[ ! -d " /root/.easykube/" ]]; then
        mkdir /root/.easykube/
    fi
    CONFIGFILE="/root/.easykube/config.json"
    CONNFILE="/root/.easykube/connections.json"
fi

if [[ ! -e $CONFIGFILE ]]; then
    touch $CONFIGFILE
    chmod 775 $CONFIGFILE
    echo '{"kubeconfig":"'$(kubectl config current-context)'"}' | jq > $CONFIGFILE
fi

if [[ ! -e $CONNFILE ]]; then
    touch $CONNFILE
    chmod 775 $CONNFILE
    echo '[]' | jq > $CONNFILE
fi
#TABLEVIEW=$(awk '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}') #why the fuck it isn't works?..
table6(){
    awk '{printf "%-0s %-5s %-60s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
}

table3(){
    awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
}

dbPass(){
    #in future - make a json map for secrets
    dbHelp(){
        echo "Usage:
    easykube db [namespace] [action]"
        echo "Actions:
    pass - show db password
    connect - connect to db
    dump - make db dump"
        exit 1
    }

    showDbPass(){
        echo "$NS DB PASSWORD:"
        echo $DBPASS
        exit 0
    }

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    NS=$2
    DBPASS=$(kubectl -n $NS get secret db-postgresql -o=jsonpath='{.data.postgresql-password}' | base64 -d || echo "Could not find secret" && exit 1)

    case $3 in
        connect) dbConnect $NS $DBPASS
        ;;
        dump) dbDump $NS $DBPASS
        ;;
        pass) showDbPass
        ;;
        *) echo "Unknow action" && dbHelp && exit 1
        ;;
    esac

}

dbConnect(){

    NS=$1
    DBPASS=$2

    choosePod(){
        pods=$@
        echo "Select DB pod"
        for (( i=0; i<${#pods[@]}; i++ )); do
            echo "[$i]: ${pods[i]}"
        done
        read -r c
        podDb=${pods[c]}
    }

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods -l app.kubernetes.io/instance=db | grep -v "NAME" | cut -d' ' -f1))
    case ${#pods[@]} in
        0) echo "No pods found" && exit 1
        ;;
        1) podDb=${pods[0]}
        ;;
        *) choosePod ${pods[@]}
        ;;
    esac

    if [[ -z $podDb ]]; then
        choosePod ${pods[@]}
    fi
    container=$(kubectl -n $NS get pod $podDb -o=jsonpath={'.spec.containers[0].name'})
    kubectl -n $NS exec -it $podDb -c $container -- sh -c "PGPASSWORD=$DBPASS psql -U postgres"
}

dbDump(){
    NS=$1
    DBPASS=$2

    choosePod(){
        pods=$@
        echo "Select DB pod"
        for (( i=0; i<${#pods[@]}; i++ )); do
            echo "[$i]: ${pods[i]}"
        done
        read -r c
        podDb=${pods[c]}
    }

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods -l app.kubernetes.io/instance=db | grep -v "NAME" | cut -d' ' -f1))
    case ${#pods[@]} in
        0) echo "No pods found" && exit 1
        ;;
        1) podDb=${pods[0]}
        ;;
        *) choosePod ${pods[@]}
        ;;
    esac

    if [[ -z $podDb ]]; then
        choosePod ${pods[@]}
    fi

    echo -e "Enter dir where dump will be placed. Example: /tmp. Default is current directory: \c"
    read -r dumpdir
    if [[ -z $dumpdir ]]; then
        dumpdir="./"
    fi

    if [[ dumpdir == "~" ]]; then
        if [[ $USER == 'root' ]]; then
            dumpdir="/root"
        else
            dumpdir="/home/$USER"
        fi
    fi

    FILE=$dumpdir"/"$NS.$(date +%d"."%m"."%Y).sql.gz
    container=$(kubectl -n $NS get pod $podDb -o=jsonpath={'.spec.containers[0].name'})
    echo -e "${BLUE}Dumping DB $NS into $FILE ${NC}"
    kubectl -n $NS exec $podDb -c $container -- sh -c "PGPASSWORD=$DBPASS pg_dump -U postgres -Z 9 $NS" > $FILE
    echo "Done"

}

dbRestore(){
    #kubectl -n $NS sca
    #kubectl -n $NS get pod db-postgresql-0 -o json | jq ".spec.volumes [0].persistentVolumeClaim.claimName " -r
    exit 0
}

exe(){
    NS=$2
    #cmd=$3

    exeHelp(){
        echo "kubectl exec"
        echo "Usage: easykube [namespace] [command]"
        exit 1
    }

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    while [ -n "$3" ]; do
        cmd+=$3" "
        shift
    done

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" |  awk '{print $1"@"$3}'))

    echo "List of pods:"
    a=0
    for (( i=0; i<${#pods[@]}; i++ )); do

            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)

            if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
                echo -e "   ${GREEN} [$a]: $pod${NC}" | table3
                ((a++))
                exepods+=($pod)
            elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
                echo -e "   ${GRAY} [-]: $pod${NC}" | table3
            else
                echo -e "   ${RED} [-]: $pod${NC}" | table3
            fi
    done

    if [[ -z $exepods ]]; then
        echo -e "\nNo pods available" && exit 1
    fi

    echo -e "\nSelect number: \c"
    read -r c
    pod=${exepods[c]}
    container=$(kubectl -n $NS get pod $pod -o=jsonpath={'.spec.containers[0].name'})
    echo ""
    echo -e "${YELLOW}$pod selected${NC}"
    echo ""
    kubectl -n $NS exec -it $pod -c $container -- $cmd 
    exit 0

}

podLogs(){
    NS=$2

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    if [[ -z $3 ]]; then

        IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3"@"$4}'))

        echo "List of pods:"
        a=0
        for (( i=0; i<${#pods[@]}; i++ )); do

            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)

            if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
                echo -e "   ${GREEN} [$a]: $pod${NC}" | table3
                ((a++))
                exepods+=($pod)
            elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
                echo -e "   ${GRAY} [-]: $pod${NC}" | table3
            else
                echo -e "   ${RED} [$a]: $pod${NC}" | table3
                ((a++))
                exepods+=($pod)
            fi
        done

        if [[ -z $exepods ]]; then
            echo -e "\nNo pods available" && exit 1
        fi

        echo -e "\nSelect number: \c"
        read -r c
        pod=${exepods[c]}
    else
        pod=$3
    fi
    container=$(kubectl -n $NS get pod $pod -o=jsonpath={'.spec.containers[0].name'})
    echo ""
    echo -e "${YELLOW}$pod selected${NC}"
    echo ""
    kubectl -n $NS logs $pod $container
    exit 0

}

checkPods(){

    checkHelp(){
        echo "Usage: easykube check [namespase] [option] watch(optional)"
        echo "Actions:"
        echo "  all - show all state pods"
        echo "  warn - show pods with restarts"
        echo "  err - show pods with errors"
        exit 1
    }

    afterRun(){
        exepods=$@

        echo -e "\nChoose pod to view its log or press ^C: \c"
        read -r b

        if [[ -z $exepods ]]; then
            echo -e "\nNo pods available" && exit 1
        fi

        podLogs "logs" $NS ${exepods[b]}
    }

    all(){
        show(){
            a=0
            for (( i=0; i<${#pods[@]}; i++ )); do
                pod=$(echo ${pods[i]} | cut -d"@" -f1)
                podstate=$(echo ${pods[i]} | cut -d"@" -f2)
                podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
                if { [[ "${PODOK[*]}" =~ "${podstate}" && $podrestarts -gt 0 ]]; }; then
                    echo -e "   ${YELLOW} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                    ((a++))
                    exepods+=($pod)
                elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
                    echo -e "   ${DGRAY} [-]: $pod $podstate $podrestarts ${NC}" | table6
                    exepods+=($pod)
                elif [[ "${PODOK[*]}" =~ "${podstate}" ]];  then
                    echo -e "   ${GREEN} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                    ((a++))
                    exepods+=($pod)
                else
                    echo -e "   ${RED} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                    ((a++))
                    exepods+=($pod)
                fi
            done
        }

        if [[ -z $1 ]]; then
            show
            exit 0
            afterRun ${exepods[@]}
        else
            while true ; do
                tput el
                show
                if [[ -z $exepods ]]; then
                    echo -e "\nNo pods available" && exit 1
                fi
                sleep 5
            done
        fi
    }

    warn(){
        a=0
        for (( i=0; i<${#pods[@]}; i++ )); do
            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)
            podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
            if { [[ "${PODOK[*]}" =~ "${podstate}" && $podrestarts -gt 0 ]]; }; then
                echo -e "   ${YELLOW} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                ((a++))
                exepods+=($pod)
            fi
        done
        afterRun ${exepods[@]}
    }

    err(){
        a=0
        for (( i=0; i<${#pods[@]}; i++ )); do
            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)
            podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
            if [[ "${PODERR[*]}" =~ "${podstate}" ]]; then
                echo -e "   ${RED}[$a]: $pod $podstate $podrestarts ${NC}" | table6
                ((a++))
                exepods+=($pod)
            fi
        done
        afterRun ${exepods[@]}
    }

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    NS=$2

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3"@"$4}'))

    while [ -n $3 ]; do
        case $3 in
            err) err $4
            ;;
            warn) warn $4
            ;;
            all) all $4
            ;;
            *) checkHelp
            ;;
        esac
    done
}

# expose(){
#     NS=$2
#     kind=$3
#     sport=$4

#     exposeHelp(){
#         echo "Usage: easykube expose [namespace] [kind] port(optional)"
#         echo "Example: easykube expose demo svc 8080"
#         echo "Kinds:"
#         echo "  service, svc, s"
#         echo "  deployment, d"
#         echo "  pod"
#         exit 1
#     }

#     case $kind in
#         service|svc|c) resource="service"
#         ;;
#         deployment|d) resource="deployment"
#         ;;
#         pod) resource="pod"
#         ;;
#         *) exposeHelp
#         ;;
#     esac

#     IFS=" " read -a items <<< $(echo $(kubectl -n $NS get $resource"s" | grep -v "NAME" | awk '{print $1"@"$5}'))

#     if [[ -z $items ]]; then
#         echo -e "\nNo $resource"s" available" && exit 1
#     fi

#     for (( i=0; i<${#items[@]}; i++ )); do
#         item=$(echo ${items[i]} | cut -d"@" -f1)
#         port=$(echo ${items[i]} | cut -d"@" -f2 | cut -d"/" -f1)
#         echo -e "   ${GREEN} [$i]: $item${NC}" | table3
#         array+=($item)
#     done

#     echo -e "\nSelect number: \c"
#     read -r c
#     item=${array[c]}
#     echo ""

#     if [[ -z $sport ]]; then
#         sport=$port
#     fi

#     handleConnection(){
#         dir="/tmp/"
#         file="hc-$(uuidgen).sh"
#         echo "
#         CONNFILE=$(echo $CONNFILE)
#         kubectl -n $NS port-forward svc/$svc $sport/$port
#         sleep 3600
#         cat $CONNFILE | jq 'del(.connections | .[] | select(.name=='\"test1\"'))' > /tmp/easykube && cat /tmp/easykube > $CONNFILE
#         exit 0" > $dir$file
#         chmod +x $dir$file
#         # cd $dir && ./$file > /dev/null 2>&1
#         # pid=$!
#         # if [[ $? -ne 0 ]]; then
#         #     echo "Can't establish connection" && exit 1
#         # fi

#         check=cat $CONNFILE | jq '.connections | .[] | select(.name=='\"$NS\"')'
#         if [[ ! -z $check ]]; then
#             port=cat $CONNFILE | jq '.connections | .[] | select(.name=='\"$NS\"') | .port'
#             pid=cat $CONNFILE | jq '.connections | .[] | select(.name=='\"$NS\"') | .pid'
#             echo "$NS already exposed with port $port ($pid)" && exit 1
#         fi
#         echo "jq"
#         cat $CONNFILE | jq '.[] + [{"name":'\"$NS\"', "port":'\"$sport\"', "pid":'\"$pid\"'}]' #> /tmp/easykube.conf && cat /tmp/easykube.conf > $CONFIGFILE
#         echo "$resource $item available at http://127.0.0.1:$sport for a 1 hour"

#     }

#     echo ""
#     echo -e "${YELLOW}$item selected${NC}"
#     echo ""
#     #kubectl -n $NS port-forward svc/$svc $sport/$port & 2>&1 /dev/null
#     handleConnection $item $sport $port
#     exit 0
# }

thisHelp(){
    echo "Easykube."
    echo "Usage: easykube [option] [arguments]"
    echo "List of options:"
    echo "  db"
    echo "  exe"
    echo "  check, c"
    echo "  logs, l"
    # echo "  expose, e"
    echo "  help, h"
    echo "  version, v"
}

version(){
    echo "easykube 1.0b"
}

if [[ $(kubectl config current-context) =~ "prod" ]]; then
    echo -e "${RED}ATTENTION"
    echo "PRODUCTION KUBECONFIG IS IN USE"
    echo -e "PLEASE BE CAREFULL${NC}\n"
fi

while [ -n "$1" ]; do
    case $1 in
        db) dbPass $1 $2 $3 #option, ns, next call
        break ;;
        exe|exec) exe $1 $2 $3 #option, ns command
        break ;;
        check | c) checkPods "check" $2 $3 $4
        break ;;
        logs | l) podLogs "logs" $2 #option, ns
        break ;;
        # expose | e) expose "expose" $2 $3 $4 $5 #option, ns, kind,
        # break ;;
        version | v) version
        break ;;
        *) thisHelp
        break ;;
    esac
done