#!/bin/bash

#TODO:
#   expose port:
#       pod
#       svc
#       deployment

###COLORLS###
#LIGHT COLORS#
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
GRAY='\033[0;37m'
#REGULAR COLORS#
DGRAY='\033[0;30m'
BLACK='\033[30m'
DRED='\033[31m'
YELLOW='\033[0;33m'
NC='\033[0m' #No color

###POD STATES###
PODOK=("Running")
PODERR=("CrashLoopBackOff" "Error" "Failed" "ImagePullBackOff" "ErrImagePull" "Unknow")
PODNONE=("Completed" "Terminating" "Init" "Waiting" "Pending" "ContainerCreating")

trap 'tput cnorm; echo' EXIT

#TABLEVIEW=$(awk '{printf "%-0s %-5s %-50s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}') #why the fuck it isn't works?..
table6(){
    awk '{printf "%-0s %-5s %-60s %-25s %-5s %-0s\n" ,$1,$2,$3,$4,$5,$6}'
}

table3(){
    awk '{printf "%-0s %-5s %-50s\n" ,$1,$2,$3}'
}

dbPass(){
    #in future - make a json map for secrets
    dbHelp(){
        echo "Usage:
    easykube db [namespace] [action]"
        echo "Actions:
    pass - show db password
    connect - connect to db
    dump - make db dump"
        exit 1
    }

    showDbPass(){
        echo "$NS DB PASSWORD:"
        echo $DBPASS
        exit 0
    }

    
    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    NS=$2
    DBPASS=$(kubectl -n $NS get secret db-postgresql -o=jsonpath='{.data.postgresql-password}' | base64 -d || echo "Could not find secret" && exit 1)

    case $3 in
        connect) dbConnect $NS $DBPASS
        ;;
        dump) dbDump $NS $DBPASS
        ;;
        pass) showDbPass
        ;;
        *) echo "Unknow action" && dbHelp && exit 1
        ;;
    esac

}

dbConnect(){

    NS=$1
    DBPASS=$2

    choosePod(){
        pods=$@
        echo "Select DB pod"
        for (( i=0; i<${#pods[@]}; i++ )); do
            echo "[$i]: ${pods[i]}"
        done
        read -r c
        podDb=${pods[c]}
    }

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods -l app.kubernetes.io/instance=db | grep -v "NAME" | cut -d' ' -f1))
    case ${#pods[@]} in
        0) echo "No pods found" && exit 1
        ;;
        1) podDb=${pods[0]}
        ;;
        *) choosePod ${pods[@]}
        ;;
    esac

    if [[ -z $podDb ]]; then
        choosePod ${pods[@]}
    fi
    container=$(kubectl -n $NS get pod $podDb -o=jsonpath={'.spec.containers[0].name'})
    kubectl -n $NS exec -it $podDb -c $container -- sh -c "PGPASSWORD=$DBPASS psql -U postgres"
}

dbDump(){
    NS=$1
    DBPASS=$2

    choosePod(){
        pods=$@
        echo "Select DB pod"
        for (( i=0; i<${#pods[@]}; i++ )); do
            echo "[$i]: ${pods[i]}"
        done
        read -r c
        podDb=${pods[c]}
    }

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods -l app.kubernetes.io/instance=db | grep -v "NAME" | cut -d' ' -f1))
    case ${#pods[@]} in
        0) echo "No pods found" && exit 1
        ;;
        1) podDb=${pods[0]}
        ;;
        *) choosePod ${pods[@]}
        ;;
    esac

    if [[ -z $podDb ]]; then
        choosePod ${pods[@]}
    fi

    echo -e "Enter dir where dump will be placed. Example: /tmp. Default is current directory: \c"
    read -r dumpdir
    if [[ -z $dumpdir ]]; then
        dumpdir="./"
    fi

    if [[ dumpdir == "~" ]]; then
        if [[ $USER == 'root' ]]; then
            dumpdir="/root"
        else
            dumpdir="/home/$USER"
        fi
    fi

    FILE=$dumpdir"/"$NS.$(date +%d"."%m"."%Y).sql.gz
    container=$(kubectl -n $NS get pod $podDb -o=jsonpath={'.spec.containers[0].name'})
    echo -e "${BLUE}Dumping DB $NS into $FILE ${NC}"
    kubectl -n $NS exec $podDb -c $container -- sh -c "PGPASSWORD=$DBPASS pg_dump -U postgres -Z 9 $NS" > $FILE
    echo "Done"

}

exe(){
    NS=$2
    cmd=$3

    exeHelp(){
        echo "kubectl exec"
        echo "Usage: easykube [namespace] [command]"
        exit 1
    }

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" |  awk '{print $1"@"$3}'))

    echo "List of pods:"
    a=0
    for (( i=0; i<${#pods[@]}; i++ )); do

            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)

            if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
                echo -e "   ${GREEN} [$a]: $pod${NC}" | table3
                ((a++))
                exepods+=($pod)
            elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
                echo -e "   ${GRAY} [-]: $pod${NC}" | table3
            else
                echo -e "   ${RED} [-]: $pod${NC}" | table3
            fi
    done

    if [[ -z $exepods ]]; then
        echo -e "\nNo pods available" && exit 1
    fi

    echo -e "\nSelect number: \c"
    read -r c
    pod=${exepods[c]}
    container=$(kubectl -n $NS get pod $pod -o=jsonpath={'.spec.containers[0].name'})
    echo ""
    echo -e "${YELLOW}$pod selected${NC}"
    echo ""
    kubectl -n $NS exec -it $pod -c $container -- $cmd 
    exit 0

}

podLogs(){
    NS=$2

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    if [[ -z $3 ]]; then

        IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3"@"$4}'))

        echo "List of pods:"
        a=0
        for (( i=0; i<${#pods[@]}; i++ )); do

            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)

            if [[ "${PODOK[*]}" =~ "${podstate}" ]]; then
                echo -e "   ${GREEN} [$a]: $pod${NC}" | table3
                ((a++))
                exepods+=($pod)
            elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
                echo -e "   ${GRAY} [-]: $pod${NC}" | table3
            else
                echo -e "   ${RED} [$a]: $pod${NC}" | table3
                ((a++))
                exepods+=($pod)
            fi
        done

        if [[ -z $exepods ]]; then
            echo -e "\nNo pods available" && exit 1
        fi

        echo -e "\nSelect number: \c"
        read -r c
        pod=${exepods[c]}
    else
        pod=$3
    fi
    container=$(kubectl -n $NS get pod $pod -o=jsonpath={'.spec.containers[0].name'})
    echo ""
    echo -e "${YELLOW}$pod selected${NC}"
    echo ""
    kubectl -n $NS logs $pod $container
    exit 0

}


checkPods(){

    tput sc

    checkHelp(){
        echo "Usage: easykube check [namespase] [option] watch(optional)"
        echo "Actions:"
        echo "  all - show all state pods"
        echo "  warn - show pods with restarts"
        echo "  err - show pods with errors"
        exit 1
    }

    afterRun(){
        exepods=$@

        echo -e "\nChoose pod to view its log or press ^C: \c"
        read -r b

        podLogs "logs" $NS ${exepods[b]}
    }

    all(){
        show(){
            tput rc
            a=0
            for (( i=0; i<${#pods[@]}; i++ )); do
                pod=$(echo ${pods[i]} | cut -d"@" -f1)
                podstate=$(echo ${pods[i]} | cut -d"@" -f2)
                podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
                if { [[ "${PODOK[*]}" =~ "${podstate}" && $podrestarts -gt 0 ]]; }; then
                    echo -e "   ${YELLOW} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                    ((a++))
                    exepods+=($pod)
                elif [[ "${PODNONE[*]}" =~ "${podstate}"  ]]; then
                    echo -e "   ${DGRAY} [-]: $pod $podstate $podrestarts ${NC}" | table6
                    exepods+=($pod)
                elif [[ "${PODOK[*]}" =~ "${podstate}" ]];  then
                    echo -e "   ${GREEN} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                    ((a++))
                    exepods+=($pod)
                else
                    echo -e "   ${RED} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                    ((a++))
                    exepods+=($pod)
                fi
            done
            if [[ -z $exepods ]]; then
                echo -e "\nNo pods available" && exit 1
            fi
        }

        if [[ -z $1 ]]; then
            show
            afterRun ${exepods[@]}
        else
            tput civis
            while [ true ]; do
                show
                sleep 5
            done
        fi
    }

    warn(){
        a=0
        for (( i=0; i<${#pods[@]}; i++ )); do
            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)
            podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
            if { [[ "${PODOK[*]}" =~ "${podstate}" && $podrestarts -gt 0 ]]; }; then
                echo -e "   ${YELLOW} [$a]: $pod $podstate $podrestarts ${NC}" | table6
                ((a++))
                exepods+=($pod)
            fi
        done
        afterRun ${exepods[@]}
    }

    err(){
        a=0
        for (( i=0; i<${#pods[@]}; i++ )); do
            pod=$(echo ${pods[i]} | cut -d"@" -f1)
            podstate=$(echo ${pods[i]} | cut -d"@" -f2)
            podrestarts=$(echo ${pods[i]} | cut -d"@" -f3)
            if [[ "${PODERR[*]}" =~ "${podstate}" ]]; then
                echo -e "   ${RED}[$a]: $pod $podstate $podrestarts ${NC}" | table6
                ((a++))
                exepods+=($pod)
            fi
        done
        afterRun ${exepods[@]}
    }

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    NS=$2

    IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$3"@"$4}'))


            tput sc
    #
        while [ -n $3 ]; do
            case $3 in
                err) err $4
                ;;
                warn) warn $4
                ;;
                all) all $4
                ;;
                *) checkHelp
                ;;
            esac
        done
}

expose(){
    NS=$2
    kind=$3
    exposeHelp(){
        echo "Usage: easykube expose [namespace] [kind] port(optional)"
        echo "Example: easykube expose demo svc 8080"
        echo "Kinds:"
        echo "  service, svc, s"
        echo "  deployment, d"
        echo "  pod"
        exit 1
    }

    handleConnection(){
        NS=$1
        name=$2
        sport=$3
        port=$4
        file="hc-$(uuidgen)"

        echo "kubectl -n $NS port-forward svc/$name $sport/$port & 2>&1 /dev/null" > "/tmp/$file"
        chmod +x "/tmp/$file"
        ./tmp/$file > /dev/null 2>&1 && hcpid=$?
        echo [] | jq '. + [{"defaults":{"name":'\"$name\"', "port":'\"$port\"', "pid":'\"$hcpid\"'}}]' > $DEFAULTSFILE


    }

    exposeSvc(){
        IFS=" " read -a svcs <<< $(echo $(kubectl -n $NS get services | grep -v "NAME" | awk '{print $1"@"$5}'))

        if [[ -z $svcs ]]; then
            echo -e "\nNo pods available" && exit 1
        fi

        for (( i=0; i<${#svcs[@]}; i++ )); do
            svc=$(echo ${svcs[i]} | cut -d"@" -f1)
            port=$(echo ${svcs[i]} | cut -d"@" -f2 | cut -d"/" -f1)
            echo -e "   ${GREEN} [$i]: $pod${NC}" | table3
        done

        echo -e "\nSelect number: \c"
        read -r c
        svc=${svcs[c]}
        echo ""

        case $4 in
            port) sport=$5
            ;;
        esac
        if [[ -z $sport ]]; then
            echo -e "Local port (or leave empty): \c"
            read -r sport
            if [[ -z $sport ]]; then
                sport=$port
            fi
        fi
        echo ""
        echo -e "${YELLOW}$pod selected${NC}"
        echo ""
        #kubectl -n $NS port-forward svc/$svc $sport/$port & 2>&1 /dev/null
        handleConnection $NS $svc $sport $port
        exit 0
    }

    exposeDeployment(){
        IFS=" " read -a deployments <<< $(echo $(kubectl -n $NS get deployments | grep -v "NAME" | awk '{print $1"@"$5}'))

        if [[ -z $deployments ]]; then
            echo -e "\nNo deployments available" && exit 1
        fi

        for (( i=0; i<${#deployments[@]}; i++ )); do
            dp=$(echo ${deployments[i]} | cut -d"@" -f1)
            port=$(echo ${deployments[i]} | cut -d"@" -f2 | cut -d"/" -f1)
            echo -e "   ${GREEN} [$i]: $dp${NC}" | table3
        done

        echo -e "\nSelect number: \c"
        read -r c
        deployment=${deployments[c]}
        echo ""

        case $4 in
            port) sport=$5
            ;;
        esac
        if [[ -z $sport ]]; then
            echo -e "Local port (or leave empty): \c"
            read -r sport
            if [[ -z $sport ]]; then
                sport=$port
            fi
        fi
        echo ""
        echo -e "${YELLOW}$pod selected${NC}"
        echo ""
        kubectl -n $NS port-forward deployment/$deployment $sport/$port & 2>&1 /dev/null
        exit 0
    }

    exposePod(){
        IFS=" " read -a pods <<< $(echo $(kubectl -n $NS get pods | grep -v "NAME" | awk '{print $1"@"$5}'))

        if [[ -z $pods ]]; then
            echo -e "\nNo pods available" && exit 1
        fi

        for (( i=0; i<${#pods[@]}; i++ )); do
            dp=$(echo ${pods[i]} | cut -d"@" -f1)
            port=$(echo ${pods[i]} | cut -d"@" -f2 | cut -d"/" -f1)
            echo -e "   ${GREEN} [$i]: $dp${NC}" | table3
        done

        echo -e "\nSelect number: \c"
        read -r c
        pod=${pods[c]}
        echo ""

        case $4 in
            port) sport=$5
            ;;
        esac
        if [[ -z $sport ]]; then
            echo -e "Local port (or leave empty): \c"
            read -r sport
            if [[ -z $sport ]]; then
                sport=$port
            fi
        fi
        echo ""
        echo -e "${YELLOW}$pod selected${NC}"
        echo ""
        kubectl -n $NS port-forward pods/$pod $sport/$port & 2>&1 /dev/null
        exit 0
    }

    if { [[ $2 =~ "help" ]] || [[ -z $3 || -z $2 ]]; }; then
        if [[ -z $2 ]]; then
            echo -e "${RED}Namespace is not defined${NC}"
        fi
        $1Help
    fi

    case $2 in
        service|svc|c) exposeSvc
        break ;;
        deployment|d) exposeDeployment
        break ;;
        pod) exposePod
        break ;;
        *) exposeHelp
        break ;;
    esac
}

thisHelp(){
    echo "Easykube."
    echo "Usage: easykube [option] [arguments]"
    echo "List of options:"
    echo "  db"
    echo "  exe"
    echo "  check, c"
    echo "  logs, l"
    # echo "  expose, e"
    echo "  help, h"
    echo "  version, v"
}

version(){
    echo "easykube 1.0b"
}

if [[ $(kubectl config current-context) =~ "prod" ]]; then
    echo -e "${RED}ATTENTION"
    echo "PRODUCTION KUBECONFIG IS IN USE"
    echo -e "PLEASE BE CAREFULL${NC}\n"
fi

while [ -n "$1" ]; do
    case $1 in
        db) dbPass $1 $2 $3 #option, ns, next call
        break ;;
        exe) exe $1 $2 $3 #option, ns command
        break ;;
        check | c) checkPods $1 $2 $3 $4
        break ;;
        logs | l) podLogs $1 $2 #option, ns
        break ;;
        # expose | e) exposePort $1 $2 $3 $4 $5 #option, ns, kind,
        # break ;;
        version | v) version
        break ;;
        *) thisHelp
        break ;;
    esac
done